### ISSUE TITLE
URL building issue

### ISSUE THREAD

**Issue by jffz** [pschmitt/pyteleloisirs#2]
Not sure of what is happening here but looks like the url building fails at some points.
Triple checked my DNS, tried to fix the host in my hosts file wihtout success.

```py
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.async_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/liveboxplaytv/media_player.py", line 98, in async_update
    self._client.async_get_current_program()
  File "/srv/homeassistant/lib/python3.5/site-packages/liveboxplaytv/liveboxplaytv.py", line 139, in async_get_current_program
    return (yield from async_get_cprg(self.channel))
  File "/srv/homeassistant/lib/python3.5/site-packages/pyteleloisirs/pyteleloisirs.py", line 240, in async_get_current_program
    guide = await async_get_program_guide(chan, no_cache)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyteleloisirs/pyteleloisirs.py", line 227, in async_get_program_guide
    programs = await asyncio.gather(*tasks)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyteleloisirs/pyteleloisirs.py", line 167, in async_set_summary
    resp = await session.get(program.get('url'))
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.programme-tv.nethttps:80 ssl:None [Name or service not known]
```

**Comment by jffz** [comment]
After some digging, looks like the issue is on https://github.com/pschmitt/pyteleloisirs/blob/master/pyteleloisirs/pyteleloisirs.py#L202
I could do a PR if you want but removing this part just should do the trick for now.

**Comment by vincent-k** [comment]
Thanks @jffz, this fixed the issue (https://github.com/pschmitt/pyteleloisirs/pull/3).
