### ISSUE TITLE
Erreur lors de la récupération du programme TV

### ISSUE THREAD

**Issue by bnounours** [pschmitt/pyteleloisirs#6]
Bonjour Philipp,

J'utilise indirectement ton module via Home Assistant (https://github.com/home-assistant/home-assistant/issues/31503)
Il semblerait que le site ai changé de format et que la balise "h1" que tu cherches ne soit plus présente. cela fait planter l'intégration avec le STB d'orange que j'utilise.

Si tu as un peu de temps est ce que tu peux jeter un oeil ?

Voici la trace dans homeassistant
```
2020-02-05 22:45:31 ERROR (MainThread) [homeassistant.components.media_player] liveboxplaytv: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyteleloisirs/pyteleloisirs.py", line 155, in extract_program_summary
    'div', {'class': 'episode-synopsis'}
AttributeError: 'NoneType' object has no attribute 'find_all'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 299, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/liveboxplaytv/media_player.py", line 116, in async_update
    program = await self._client.async_get_current_program()
  File "/usr/local/lib/python3.7/site-packages/liveboxplaytv/liveboxplaytv.py", line 142, in async_get_current_program
    return (yield from async_get_cprg(self.channel))
  File "/usr/local/lib/python3.7/site-packages/pyteleloisirs/pyteleloisirs.py", line 247, in async_get_current_program
    guide = await async_get_program_guide(chan, no_cache)
  File "/usr/local/lib/python3.7/site-packages/pyteleloisirs/pyteleloisirs.py", line 234, in async_get_program_guide
    programs = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/site-packages/pyteleloisirs/pyteleloisirs.py", line 171, in async_set_summary
    summary = extract_program_summary(text)
  File "/usr/local/lib/python3.7/site-packages/pyteleloisirs/pyteleloisirs.py", line 159, in extract_program_summary
    soup.find('h1').text.strip())
AttributeError: 'NoneType' object has no attribute 'text'
```
Merci,

**Comment by pschmitt** [comment]
Please don't comment in French.
Fixed by #7
